### PR TITLE
Add VimuxCurrentLine to send current line to runner pane

### PR DESCRIPTION
**Pull request by chu-**
Send content of current line to the runner pane then run.

### CODE REVIEW

**Comment by benmills** [comment]
@chu- Generally I've been against adding things like this to vimux. I'd prefer to see this as a plugin built on top of vimux. 

My thought is vimux should just provide enough functionality to interface with tmux and nothing more. What do you think?

**Comment by chu-** [comment]
@benmills Yes, I agree with you.

**Comment by michaelfresco** [comment]
Damn, this would really solve my problem. How would one go about implementing this manually? I am not a vim expert. Does anyone know a simple script that I could add to my .vimrc to get that command? 

yanking lines, and sending them to a tmux pane, is what i am trying to achieve.

**Comment by michaelfresco** [comment]
@chu- thanks a bunch for making your fork! You really saved my ass. I had a hard time understanding how vimux works, and I don't understand (honestly) why this is not built-in by default.

**Pull request closed without merging**
